# Error Codes
NO_FACE_DETECTED = "NO_FACE_DETECTED"
MULTIPLE_FACES = "MULTIPLE_FACES"
FACE_OBSTRUCTED = "FACE_OBSTRUCTED"
LOW_QUALITY = "LOW_QUALITY"

# Result Codes
MATCH_RESULT = "COINCIDENCIA_SUFICIENTE"
NO_MATCH_RESULT = "EVIDENCIA_INSUFICIENTE"

# Thresholds
MIN_FACE_SCORE = 0.5  # InsightFace detection score minimum
DEFAULT_COSINE_THRESHOLD = 0.45

# Image Limits
MAX_IMAGE_SIZE_MB = 5
MIN_IMAGE_DIMENSION = 480
MAX_IMAGE_SIZE_BYTES = MAX_IMAGE_SIZE_MB * 1024 * 1024
